### ISSUE TITLE
Bug: Wrong sign in equation

### ISSUE THREAD

**Issue by rolavick** [alisw/STARlight#6]
https://github.com/alisw/STARlight/blob/67efd37ed0f21ce139cbb929ce551d7860ef2104/HepMC/starlight2hepmc.awk#L6C1-L6C1

Instead of minus it should be plus

**Comment by sawenzel** [comment]
please make a pull request

**Comment by rolavick** [comment]
this PR should fix it https://github.com/alisw/STARlight/pull/7
